### ISSUE TITLE
Module cycloidbox has no class pindiskClass

### ISSUE THREAD

**Issue by knipknap** [iplayfast/CycloidGearBox#10]
After installation from master, I am trying to open this file:

https://www.printables.com/model/45292-cycloidal-gear-box

I see the following in the console:

```
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class pindiskClass
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class cycdiskClass
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class driver_diskClass
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class EccShaft
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class EccKey
23:54:04  <class 'AttributeError'>: Module cycloidbox has no class OutShaft
```

Version info:

```
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33357 (Git) Snap 721
Build type: Release
Branch: master
Hash: f0560ac2078ad71b4c97b74281990bb916431da9
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * Manipulator 1.5.0
  * DynamicData 2.46.0
  * toSketch 1.0.1
  * fasteners 0.4.56
  * lattice2 1.0.0
  * Assembly3 0.12.0
  * sheetmetal 0.2.63
  * CycloidGearBox
  * Assembly4 0.50.2
```

**Comment by knipknap** [comment]
I now found the sample in the Repository under "Defaultoutput", and when opening that I do not see the errors, so I suspect the linked file on Printables is just no longer compatible.

However, the one from the repository also creates an error, but only when changing a parameter:

```
00:01:51  Traceback (most recent call last):
00:01:51    File "/home/asd/snap/freecad/common/Mod/CycloidGearBox/cycloidbox.py", line 260, in recompute
00:01:51      cycloidFun.generate_parts(App.ActiveDocument, self.GetParameters())
00:01:51    File "/home/asd/snap/freecad/common/Mod/CycloidGearBox/cycloidbox.py", line 223, in GetParameters
00:01:51      parameters = {"tooth_count": int(self.Object.__getattribute__("tooth_count")),
00:01:51  AttributeError: 'CycloidalGearBox' object has no attribute 'Object'
```

**Comment by iplayfast** [comment]
I believe this has been fixed, reopen if you still see the problem.
